---
- name: Install "yarn" package globally.
  npm:
    name: yarn
    global: true
  environment:
    PATH: "{{ lookup('env','PATH') }}"

- name: Create a symbolic link to yarn
  file:
    src: /Users/{{ work_user }}/.nvm/versions/node/{{ nvm_node_version }}/bin/yarn
    dest: /usr/local/bin/yarn
    state: link
