---
- name: Copy yarn install script
  template: src=yarn.sh.j2 dest=/Users/{{ work_user }}/yarn.sh mode=0777

- name: Run install yarn
  command: zsh /Users/{{ work_user }}/yarn.sh
  changed_when: false
