---
- name: Copy yarn install script
  template: src=yarn.sh dest=/Users/{{ work_user }}/{{ work_dir }} mode=0777

- name: Run install yarn
  command: zsh /Users/{{ work_user }}/{{ work_dir }}/yarn.sh
  changed_when: false
