---
- name: Install nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.35.1/install.sh | zsh
    creates=/Users/{{ work_user }}/.nvm/nvm.sh
  args:
    warn: false

- name: Install node and set default version
  shell: >
    /bin/zsh -c "source ~/.nvm/nvm.sh && nvm install v10 && nvm alias default v10"
    creates=/Users/{{ work_user }}/.nvm/alias

- name: source zshrc
  become: no
  shell: source ~/.zshrc
  args:
    executable: /bin/bash
