---
- name: Install nvm
  shell: >
    set -o pipefail
    curl -o- https://raw.githubusercontent.com/creationix/nvm/{{ nvm_version }}/install.sh | zsh
    creates=/Users/{{ work_user }}/.nvm/nvm.sh
  args:
    warn: false
  changed_when: false

- name: Install node and set default version
  shell: >
    /bin/zsh -c "source ~/.nvm/nvm.sh && nvm install {{ node_version }} && nvm alias default {{ node_version }}"
    creates=/Users/{{ work_user }}/.nvm/alias
  changed_when: false

- name: source zshrc
  become: false
  command: source ~/.zshrc
  changed_when: false
